### ISSUE TITLE
new versions support

### ISSUE THREAD

**Issue by artemijan** [pioug/md-virtual-repeater#3]
Hello. First of all thanks for such library that allows render large data sets without performance issues.
 
I'm gonna to use this library in my project. And i just want to ask you about current version of angular-material captured in this library (actually virtualRepeat directive from angular material). And do you plan to support new releases from angular-material repo? 
For example there is [new release](https://github.com/angular/material/compare/v1.1.3...v1.1.4) with bug fixes for virtualRepeat.
Thanks.

**Comment by pioug** [comment]
Oh I didn't know there were bug fixes in the main repo. I will update when I'll have time. Probably next week.

**Comment by artemijan** [comment]
thanks a lot.

**Comment by pioug** [comment]
Fixed in https://github.com/pioug/md-virtual-repeater/pull/4
